server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project
    username: dasol
    password: '0417'
    
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.example.vo
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml


